/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Data.DatabaseHelper;
import Data.ShareData;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JFrame;

/**
 *
 * @author 54321
 */
public class MenuView extends javax.swing.JFrame {

    private QLnhanvienView nvView;
    private GiaoDichDatView gddView;
    private KhachHangView khachhang;
    private ThongKeView tkv;
    private GiaoDichNhaView gdnView;

    /**
     * Creates new form MenuView
     */
    public MenuView() {
        initComponents();

        setLocationRelativeTo(null);
        setExtendedState(getExtendedState() | JFrame.MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToolBar1 = new javax.swing.JToolBar();
        btnLogout = new javax.swing.JButton();
        jSeparator4 = new javax.swing.JToolBar.Separator();
        btndat = new javax.swing.JButton();
        btnnha = new javax.swing.JButton();
        jSeparator5 = new javax.swing.JToolBar.Separator();
        btnnhanvien = new javax.swing.JButton();
        jSeparator6 = new javax.swing.JToolBar.Separator();
        btnkhachang = new javax.swing.JButton();
        jSeparator7 = new javax.swing.JToolBar.Separator();
        btnthongke = new javax.swing.JButton();
        jSeparator10 = new javax.swing.JToolBar.Separator();
        mnu_GioiThieu = new javax.swing.JButton();
        jSeparator11 = new javax.swing.JToolBar.Separator();
        tplMain = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        lblten = new javax.swing.JLabel();
        lblchucvu = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnThoat = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        mnudangXuat = new javax.swing.JMenu();
        mnu_login = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        menu_edit = new javax.swing.JMenuItem();
        menu_sd = new javax.swing.JMenu();
        menu_NhanVien = new javax.swing.JMenuItem();
        jSeparator3 = new javax.swing.JPopupMenu.Separator();
        menu_KhachHang = new javax.swing.JMenuItem();
        jSeparator8 = new javax.swing.JPopupMenu.Separator();
        jSeparator9 = new javax.swing.JPopupMenu.Separator();
        Menu_QLDat = new javax.swing.JMenuItem();
        menu_QLNha = new javax.swing.JMenuItem();
        mnu_gioithieu = new javax.swing.JMenu();
        jMenuItem6 = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        jMenuItem7 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jToolBar1.setRollover(true);

        btnLogout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/logout-icon-32.png"))); // NOI18N
        btnLogout.setText("Đăng Xuất");
        btnLogout.setFocusable(false);
        btnLogout.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnLogout.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });
        jToolBar1.add(btnLogout);
        jToolBar1.add(jSeparator4);

        btndat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/logodat.PNG"))); // NOI18N
        btndat.setText("Quản Lý Đất");
        btndat.setFocusable(false);
        btndat.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btndat.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btndat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndatActionPerformed(evt);
            }
        });
        jToolBar1.add(btndat);

        btnnha.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/logonha.PNG"))); // NOI18N
        btnnha.setText("Quản Lý Nhà");
        btnnha.setFocusable(false);
        btnnha.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnnha.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnnha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnnhaActionPerformed(evt);
            }
        });
        jToolBar1.add(btnnha);
        jToolBar1.add(jSeparator5);

        btnnhanvien.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/nhanvien1_1.PNG"))); // NOI18N
        btnnhanvien.setText("Quản Lý Nhân Viên");
        btnnhanvien.setFocusable(false);
        btnnhanvien.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnnhanvien.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnnhanvien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnnhanvienActionPerformed(evt);
            }
        });
        jToolBar1.add(btnnhanvien);
        jToolBar1.add(jSeparator6);

        btnkhachang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/khachahnf.PNG"))); // NOI18N
        btnkhachang.setText("Quản lý khách hàng");
        btnkhachang.setFocusable(false);
        btnkhachang.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnkhachang.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnkhachang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnkhachangActionPerformed(evt);
            }
        });
        jToolBar1.add(btnkhachang);
        jToolBar1.add(jSeparator7);

        btnthongke.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/thongke.PNG"))); // NOI18N
        btnthongke.setText("Thống kê");
        btnthongke.setFocusable(false);
        btnthongke.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnthongke.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnthongke.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnthongkeActionPerformed(evt);
            }
        });
        jToolBar1.add(btnthongke);
        jToolBar1.add(jSeparator10);

        mnu_GioiThieu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Actions-help-about-icon-32.png"))); // NOI18N
        mnu_GioiThieu.setText("Giới thiệu");
        mnu_GioiThieu.setFocusable(false);
        mnu_GioiThieu.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        mnu_GioiThieu.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        mnu_GioiThieu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnu_GioiThieuActionPerformed(evt);
            }
        });
        jToolBar1.add(mnu_GioiThieu);
        jToolBar1.add(jSeparator11);

        lblten.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lblten.setText("jLabel1");

        lblchucvu.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lblchucvu.setText("jLabel2");

        jLabel1.setText("Người đăng nhập:");

        jLabel2.setText("Vai trò: ");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblten, javax.swing.GroupLayout.DEFAULT_SIZE, 257, Short.MAX_VALUE)
                    .addComponent(lblchucvu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(30, 30, 30))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblten)
                    .addComponent(jLabel1))
                .addGap(11, 11, 11)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblchucvu)
                    .addComponent(jLabel2))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        btnThoat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Button-Close-icon-16.png"))); // NOI18N
        btnThoat.setText("Thoát ");
        btnThoat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThoatActionPerformed(evt);
            }
        });

        mnudangXuat.setText("Hệ Thống");

        mnu_login.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_U, java.awt.event.InputEvent.CTRL_MASK));
        mnu_login.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/logout-icon-32.png"))); // NOI18N
        mnu_login.setText("Đăng Xuất");
        mnu_login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnu_loginActionPerformed(evt);
            }
        });
        mnudangXuat.add(mnu_login);
        mnudangXuat.add(jSeparator1);

        menu_edit.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_X, java.awt.event.InputEvent.CTRL_MASK));
        menu_edit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/close.png"))); // NOI18N
        menu_edit.setText("Thoát");
        menu_edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_editActionPerformed(evt);
            }
        });
        mnudangXuat.add(menu_edit);

        jMenuBar1.add(mnudangXuat);

        menu_sd.setText("Quản lý");

        menu_NhanVien.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_T, java.awt.event.InputEvent.CTRL_MASK));
        menu_NhanVien.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Apps-preferences-desktop-user-password-icon-16.png"))); // NOI18N
        menu_NhanVien.setText("Quản Lý Nhân Viên");
        menu_NhanVien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_NhanVienActionPerformed(evt);
            }
        });
        menu_sd.add(menu_NhanVien);
        menu_sd.add(jSeparator3);

        menu_KhachHang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Person-Male-Light-icon-16.png"))); // NOI18N
        menu_KhachHang.setText("Quản Lý Khách Hàng");
        menu_KhachHang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_KhachHangActionPerformed(evt);
            }
        });
        menu_sd.add(menu_KhachHang);
        menu_sd.add(jSeparator8);
        menu_sd.add(jSeparator9);

        Menu_QLDat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Actions-view-choose-icon-24.png"))); // NOI18N
        Menu_QLDat.setText("Quản Lý Đất");
        Menu_QLDat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Menu_QLDatActionPerformed(evt);
            }
        });
        menu_sd.add(Menu_QLDat);

        menu_QLNha.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Home-icon-16.png"))); // NOI18N
        menu_QLNha.setText("Quản Lý Nhà");
        menu_QLNha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_QLNhaActionPerformed(evt);
            }
        });
        menu_sd.add(menu_QLNha);

        jMenuBar1.add(menu_sd);

        mnu_gioithieu.setText("Trợ Giúp");
        mnu_gioithieu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnu_gioithieuActionPerformed(evt);
            }
        });

        jMenuItem6.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F1, 0));
        jMenuItem6.setText("Nội Dung");
        mnu_gioithieu.add(jMenuItem6);
        mnu_gioithieu.add(jSeparator2);

        jMenuItem7.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F1, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem7.setText("Giới thiệu");
        jMenuItem7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem7ActionPerformed(evt);
            }
        });
        mnu_gioithieu.add(jMenuItem7);

        jMenuBar1.add(mnu_gioithieu);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 833, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnThoat))
                    .addComponent(tplMain, javax.swing.GroupLayout.DEFAULT_SIZE, 1410, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnThoat, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(9, 9, 9)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tplMain, javax.swing.GroupLayout.DEFAULT_SIZE, 1396, Short.MAX_VALUE)
                .addGap(19, 19, 19))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mnu_loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnu_loginActionPerformed
        btnLogoutActionPerformed(evt);

    }//GEN-LAST:event_mnu_loginActionPerformed

    private void menu_editActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_editActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_menu_editActionPerformed

    private void menu_NhanVienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_NhanVienActionPerformed
        btnnhanvienActionPerformed(evt);
    }//GEN-LAST:event_menu_NhanVienActionPerformed

    private void menu_KhachHangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_KhachHangActionPerformed
        btnkhachangActionPerformed(evt);
    }//GEN-LAST:event_menu_KhachHangActionPerformed

    private void jMenuItem7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem7ActionPerformed


    }//GEN-LAST:event_jMenuItem7ActionPerformed

    private void mnu_gioithieuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnu_gioithieuActionPerformed


    }//GEN-LAST:event_mnu_gioithieuActionPerformed

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        DangNhapView dn=new DangNhapView();
        dn.setVisible(true);


    }//GEN-LAST:event_btnLogoutActionPerformed

    private void btndatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndatActionPerformed
        if (gddView == null) {
            try {
                gddView = new GiaoDichDatView();
            } catch (Exception ex) {
                Logger.getLogger(MenuView.class.getName()).log(Level.SEVERE, null, ex);
            }
            ImageIcon icon = new ImageIcon(getClass().getResource(""));
            tplMain.addTab("QL Đất", icon, gddView, "Giao Dịch Đất");
        }
        tplMain.setSelectedComponent(gddView);


    }//GEN-LAST:event_btndatActionPerformed

    private void btnnhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnnhaActionPerformed
        if (gdnView == null) {
            try {
                gdnView = new GiaoDichNhaView();
            } catch (Exception ex) {
                Logger.getLogger(MenuView.class.getName()).log(Level.SEVERE, null, ex);
            }
            ImageIcon icon = new ImageIcon(getClass().getResource(""));
            tplMain.addTab("QL Nhà", icon, gdnView, "Giao Dịch Nhà");
        }
        tplMain.setSelectedComponent(gdnView);
    }//GEN-LAST:event_btnnhaActionPerformed

    private void btnnhanvienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnnhanvienActionPerformed
        if (nvView == null) {
            nvView = new QLnhanvienView();
            ImageIcon icon = new ImageIcon(getClass().getResource(""));
            tplMain.addTab("Quản Lý Nhân Viên ", icon, nvView, "Quản Lý Nhân Viên");
        }
        tplMain.setSelectedComponent(nvView);

    }//GEN-LAST:event_btnnhanvienActionPerformed

    private void btnkhachangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnkhachangActionPerformed
        if (khachhang == null) {
            khachhang = new KhachHangView();
            ImageIcon icon = new ImageIcon(getClass().getResource(""));
            tplMain.addTab("Quản Lý Khách Hàng ", icon, khachhang, "Quản Lý Khách Hàng");
        }
        tplMain.setSelectedComponent(khachhang);
    }//GEN-LAST:event_btnkhachangActionPerformed

    private void btnthongkeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnthongkeActionPerformed
        if (tkv == null) {
            tkv = new ThongKeView();
            ImageIcon icon = new ImageIcon(getClass().getResource(""));
            tplMain.addTab("Thống kê ", icon, tkv, "Thống kê");
        }
        tplMain.setSelectedComponent(tkv);
    }//GEN-LAST:event_btnthongkeActionPerformed
    private void processLogin() {
        
        lblten.setText(ShareData.nguoIdangNhap.getTenND());
        lblchucvu.setText(ShareData.nguoIdangNhap.getChucVu());
        tplMain.removeAll();
        if (ShareData.nguoIdangNhap.getChucVu().equals("Quản lý")) {
            btnnha.setEnabled(true);
            btndat.setEnabled(true);
            btnLogout.setEnabled(true);
            btnkhachang.setEnabled(true);
            btnnhanvien.setEnabled(true);
            btnthongke.setEnabled(true);

        } else if (ShareData.nguoIdangNhap.getChucVu().equals("Nhân viên")) {
            btndat.setEnabled(true);
            btnkhachang.setEnabled(true);
            btnLogout.setEnabled(true);
            btnthongke.setEnabled(false);
            btnnha.setEnabled(true);
            btnnhanvien.setEnabled(false);
        }
    }
    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
//        LoginView dialog = new LoginView(this, true);
//        dialog.setVisible(true);
        processLogin();
        
    }//GEN-LAST:event_formWindowOpened

    private void Menu_QLDatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Menu_QLDatActionPerformed
        btndatActionPerformed(evt);
    }//GEN-LAST:event_Menu_QLDatActionPerformed

    private void menu_QLNhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_QLNhaActionPerformed
        btnnhaActionPerformed(evt);
    }//GEN-LAST:event_menu_QLNhaActionPerformed

    private void mnu_GioiThieuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnu_GioiThieuActionPerformed
        GioiThieuView gt=new GioiThieuView(this, true);
        gt.setVisible(true);
    }//GEN-LAST:event_mnu_GioiThieuActionPerformed

    private void btnThoatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThoatActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnThoatActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem Menu_QLDat;
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnThoat;
    private javax.swing.JButton btndat;
    private javax.swing.JButton btnkhachang;
    private javax.swing.JButton btnnha;
    private javax.swing.JButton btnnhanvien;
    private javax.swing.JButton btnthongke;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JToolBar.Separator jSeparator10;
    private javax.swing.JToolBar.Separator jSeparator11;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JPopupMenu.Separator jSeparator3;
    private javax.swing.JToolBar.Separator jSeparator4;
    private javax.swing.JToolBar.Separator jSeparator5;
    private javax.swing.JToolBar.Separator jSeparator6;
    private javax.swing.JToolBar.Separator jSeparator7;
    private javax.swing.JPopupMenu.Separator jSeparator8;
    private javax.swing.JPopupMenu.Separator jSeparator9;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JLabel lblchucvu;
    private javax.swing.JLabel lblten;
    private javax.swing.JMenuItem menu_KhachHang;
    private javax.swing.JMenuItem menu_NhanVien;
    private javax.swing.JMenuItem menu_QLNha;
    private javax.swing.JMenuItem menu_edit;
    private javax.swing.JMenu menu_sd;
    private javax.swing.JButton mnu_GioiThieu;
    private javax.swing.JMenu mnu_gioithieu;
    private javax.swing.JMenuItem mnu_login;
    private javax.swing.JMenu mnudangXuat;
    private javax.swing.JTabbedPane tplMain;
    // End of variables declaration//GEN-END:variables
}
