/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import java.awt.Image;
import java.io.File;
import java.io.IOException;
import java.util.List;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileFilter;
import javax.swing.table.DefaultTableModel;
import Dao.NhanVienDao;
import Data.DataValdator;
import Data.ImageHelper;
import Data.MessageDialogHelper;
import Model.NguoiDung;
import javax.swing.JFrame;

/**
 *
 * @author 54321
 */
public class QLnhanvienView extends javax.swing.JPanel {
    private MenuView menuView;
    private DefaultTableModel tblModel = new DefaultTableModel();
    private  byte [] personalImage;
    /**
     * Creates new form QLnhanvienView
     */
    public QLnhanvienView() {
        initComponents();
        initTable();
        LoadDataTable();
       
    }
  private  void LoadDataTable()
    {
       try
       {
           NhanVienDao dao = new NhanVienDao();
           List<NguoiDung> list =dao.findAll();  
           tblModel.setRowCount(0);
          for(NguoiDung it : list) {
               tblModel.addRow(new Object[]
               {
                   it.getMaND(), it.getTenND(), it.getNgaySinh(),
                   it.getSoDT(),it.getGioiTinh()==1? "Nam" : "Nữ",
                   it.getDiaChi(), it.getChucVu(), it.getUserName(), it.getPass()
               });
          }
          tblModel.fireTableDataChanged();                          
       }
       catch ( Exception e)     
       {
           e.printStackTrace();
           MessageDialogHelper.showErrorDialog(menuView,e.getMessage(),"Lỗi!");
       }          
    }
     // ten bnsg
    private void initTable()
    {   
        tblModel = new DefaultTableModel();
        String[] columns = new String[]{"Mã nhân viên " ,"Họ Tên ", "Ngày Sinh","Số ĐT","Gioi Tính"," Địa Chỉ","Chức vụ","UserName","PassWord"};
        tblModel.setColumnIdentifiers(columns);
        tbbang.setModel(tblModel);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtma = new javax.swing.JTextField();
        txtten = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtuser = new javax.swing.JTextField();
        txtpass = new javax.swing.JTextField();
        rdonam = new javax.swing.JRadioButton();
        rbnu = new javax.swing.JRadioButton();
        txtchucvu = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        txtsodt = new javax.swing.JTextField();
        txttuoi = new javax.swing.JFormattedTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtdiachi = new javax.swing.JTextArea();
        jPanel2 = new javax.swing.JPanel();
        lblImage = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jPanel18 = new javax.swing.JPanel();
        txtma1 = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        btntimkiem1 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        btnThemNCC = new javax.swing.JButton();
        btnSuaNCC = new javax.swing.JButton();
        btnXoaNCC = new javax.swing.JButton();
        btnReset = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbbang = new javax.swing.JTable();
        jSeparator1 = new javax.swing.JSeparator();

        jPanel9.setBorder(javax.swing.BorderFactory.createTitledBorder("Thông Tin Nhân Viên"));
        jPanel9.setLayout(null);

        jLabel2.setText("Mã Nhân Viên");
        jPanel9.add(jLabel2);
        jLabel2.setBounds(40, 40, 110, 20);

        jLabel3.setText("Tên Nhân Viên");
        jPanel9.add(jLabel3);
        jLabel3.setBounds(40, 80, 100, 20);

        jLabel4.setText("Chức Vụ");
        jPanel9.add(jLabel4);
        jLabel4.setBounds(420, 30, 80, 20);

        jLabel6.setText("Ngày sinh");
        jPanel9.add(jLabel6);
        jLabel6.setBounds(40, 120, 80, 20);

        jLabel7.setText("Giới Tính");
        jPanel9.add(jLabel7);
        jLabel7.setBounds(40, 150, 110, 30);

        jLabel8.setText("Địa chỉ");
        jPanel9.add(jLabel8);
        jLabel8.setBounds(420, 150, 90, 20);

        txtma.setEditable(false);
        txtma.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txtma.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtmaFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtmaFocusLost(evt);
            }
        });
        txtma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtmaActionPerformed(evt);
            }
        });
        jPanel9.add(txtma);
        txtma.setBounds(160, 30, 209, 30);

        txtten.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txtten.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txttenActionPerformed(evt);
            }
        });
        jPanel9.add(txtten);
        txtten.setBounds(160, 80, 209, 30);

        jLabel9.setText("Tên Đăng Nhập");
        jPanel9.add(jLabel9);
        jLabel9.setBounds(420, 70, 100, 20);

        jLabel10.setText("Mật Khẩu");
        jPanel9.add(jLabel10);
        jLabel10.setBounds(420, 100, 90, 20);

        txtuser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtuserActionPerformed(evt);
            }
        });
        jPanel9.add(txtuser);
        txtuser.setBounds(520, 62, 209, 30);

        txtpass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtpassActionPerformed(evt);
            }
        });
        jPanel9.add(txtpass);
        txtpass.setBounds(520, 100, 209, 30);

        buttonGroup1.add(rdonam);
        rdonam.setSelected(true);
        rdonam.setText("Nam");
        jPanel9.add(rdonam);
        rdonam.setBounds(160, 160, 84, 20);

        buttonGroup1.add(rbnu);
        rbnu.setText("Nữ");
        jPanel9.add(rbnu);
        rbnu.setBounds(260, 160, 83, 20);

        txtchucvu.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Chọn Chức Vụ", "Quản lý", "Nhân viên", " " }));
        txtchucvu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtchucvuActionPerformed(evt);
            }
        });
        jPanel9.add(txtchucvu);
        txtchucvu.setBounds(520, 32, 209, 20);

        jLabel11.setText("Số Điện thoại");
        jPanel9.add(jLabel11);
        jLabel11.setBounds(40, 200, 110, 20);

        txtsodt.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jPanel9.add(txtsodt);
        txtsodt.setBounds(160, 200, 209, 30);
        jPanel9.add(txttuoi);
        txttuoi.setBounds(160, 120, 125, 30);

        txtdiachi.setColumns(20);
        txtdiachi.setRows(5);
        jScrollPane1.setViewportView(txtdiachi);

        jPanel9.add(jScrollPane1);
        jScrollPane1.setBounds(520, 140, 209, 80);

        lblImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/10207-man-student-light-skin-tone-icon-64.png"))); // NOI18N
        lblImage.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblImage, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(54, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblImage, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel9.add(jPanel2);
        jPanel2.setBounds(770, 20, 210, 160);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/open-file-icon-16.png"))); // NOI18N
        jButton1.setText("Mở Hình");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel9.add(jButton1);
        jButton1.setBounds(910, 190, 100, 25);

        jPanel18.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Tìm kiếm", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14), new java.awt.Color(153, 0, 153))); // NOI18N

        txtma1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtma1KeyReleased(evt);
            }
        });

        jLabel19.setText("Tên Nhân Viên");

        btntimkiem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/search-icon-24.png"))); // NOI18N
        btntimkiem1.setText("Tìm Kiếm");
        btntimkiem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btntimkiem1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel18Layout = new javax.swing.GroupLayout(jPanel18);
        jPanel18.setLayout(jPanel18Layout);
        jPanel18Layout.setHorizontalGroup(
            jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel18Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
                .addComponent(txtma1, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(62, 62, 62)
                .addComponent(btntimkiem1)
                .addGap(54, 54, 54))
        );
        jPanel18Layout.setVerticalGroup(
            jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel18Layout.createSequentialGroup()
                .addGroup(jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtma1)
                    .addComponent(jLabel19)
                    .addComponent(btntimkiem1))
                .addContainerGap())
        );

        jPanel4.setBackground(new java.awt.Color(204, 204, 204));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "           Chức Năng", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14), new java.awt.Color(153, 0, 153))); // NOI18N

        btnThemNCC.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/add.png"))); // NOI18N
        btnThemNCC.setText("Thêm");
        btnThemNCC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemNCCActionPerformed(evt);
            }
        });

        btnSuaNCC.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Actions-document-edit-icon-16.png"))); // NOI18N
        btnSuaNCC.setText("Cập nhập");
        btnSuaNCC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaNCCActionPerformed(evt);
            }
        });

        btnXoaNCC.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Actions-edit-delete-icon-16.png"))); // NOI18N
        btnXoaNCC.setText("Xóa");
        btnXoaNCC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaNCCActionPerformed(evt);
            }
        });

        btnReset.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8_refresh_15px.png"))); // NOI18N
        btnReset.setText("Reset");
        btnReset.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnResetMouseClicked(evt);
            }
        });
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnThemNCC, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(411, 411, 411))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnSuaNCC)
                    .addComponent(btnXoaNCC, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnReset, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(btnThemNCC, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnSuaNCC)
                .addGap(18, 18, 18)
                .addComponent(btnXoaNCC, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnReset, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tbbang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbbang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbbangMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tbbang);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, 1044, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator1, javax.swing.GroupLayout.DEFAULT_SIZE, 239, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(22, 22, 22)
                                .addComponent(jPanel18, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 1095, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 206, Short.MAX_VALUE)))
                .addContainerGap(54, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel18, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(790, 790, 790)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 830, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void tbbangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbbangMouseClicked
        try
        {
            int row = tbbang.getSelectedRow();
            if(row>=0)
            {
                Integer id = (Integer) tbbang.getValueAt(row, 0);
                NhanVienDao dao = new NhanVienDao();
                NguoiDung nd = dao.findDung(id);
                if(nd!= null)
                {
                    txtma.setText("" +nd.getMaND());
                    txtten.setText(nd.getTenND());
                    txttuoi.setText("" +nd.getNgaySinh());
                    txtsodt.setText(nd.getSoDT());
                    txtdiachi.setText(nd.getDiaChi());
                    txtpass.setText(nd.getPass());
                    txtuser.setText(nd.getUserName());
                    txtchucvu.setSelectedItem(nd.getChucVu());

                    rdonam.setSelected(nd.getGioiTinh()==1 ? true:false);
                    if(nd.getHinh() !=null)
                    {
                        Image img = ImageHelper.createiImage(nd.getHinh(),"jpg");
                        lblImage.setIcon(new ImageIcon(img));
                        personalImage =nd.getHinh();
                    }
                    else
                    {
                        personalImage = nd.getHinh();
                        ImageIcon icon = new ImageIcon(
                            getClass().getResource(""));
                        lblImage.setIcon(icon);
                    }

                }
            }
        }  catch (Exception e) {
            e.printStackTrace();
            MessageDialogHelper.showErrorDialog(menuView,e.getMessage(),"Lỗi!");
        }
    }//GEN-LAST:event_tbbangMouseClicked

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
        txtma.setText("");
        txtten.setText("");
        txttuoi.setText("");
        txtsodt.setText("");
        txtdiachi.setText("");
        txtpass.setText("");
        txtuser.setText("");
        personalImage =null;
        ImageIcon icon = new ImageIcon( getClass().getResource(""));
        lblImage.setIcon(icon);
        LoadDataTable();
    }//GEN-LAST:event_btnResetActionPerformed

    private void btnResetMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnResetMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnResetMouseClicked

    private void btnXoaNCCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaNCCActionPerformed
        StringBuilder sb = new StringBuilder();
        DataValdator.CheckDL(txtma, sb, "Mã nhân viên không được để trống !");

        if( sb.length()>0)
        {
            MessageDialogHelper.showErrorDialog(this,sb.toString(), "Lỗi");
            return;
        }
        if(MessageDialogHelper.showConfirmDialog(menuView,"Bạn có muốn xóa nhân viên không","Hỏi?")== JOptionPane.NO_OPTION)
        {
            return;
        }
        try
        {

            NhanVienDao dao = new NhanVienDao();
            if(dao.delete(Integer.parseInt(txtma.getText())))
            {
                MessageDialogHelper.showMessageDialog(menuView, "Nhân viên đã đươc xóa!", "Thông báo !");
                //                btnluuActionPerformed(evt);
                LoadDataTable();
            }
            else
            {
                MessageDialogHelper.showConfirmDialog(menuView, "Nhân viên không được xóa !","Cảnh báo!");
            }

        }
        catch( Exception e)
        {
            e.printStackTrace();
            MessageDialogHelper.showErrorDialog(menuView,e.getMessage(),"Lỗi!");
        }

    }//GEN-LAST:event_btnXoaNCCActionPerformed

    private void btnSuaNCCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaNCCActionPerformed
        StringBuilder sb = new StringBuilder();
//        DataValdator.CheckDL(txtma, sb, "Mã nhân viên không được để trống !");
        DataValdator.CheckDL(txtten, sb, "Tên nhân viên không được để trống !");
        if( sb.length()>0)
        {
            MessageDialogHelper.showErrorDialog(this,sb.toString(), "Lỗi");
            return;
        }
        if(MessageDialogHelper.showConfirmDialog(menuView,"Bạn có muốn cập nhật nhân viên không","Hỏi?")== JOptionPane.NO_OPTION)
        {
            return;
        }
        try
        {
            NguoiDung nd = new NguoiDung();
            nd.setMaND(Integer.parseInt(txtma.getText()));
            nd.setTenND(txtten.getText());
            nd.setNgaySinh(txttuoi.getText());
            nd.setSoDT(txtsodt.getText());
            nd.setGioiTinh(rdonam.isSelected()?1:0);
            nd.setDiaChi(txtdiachi.getText());
            nd.setChucVu(txtchucvu.getSelectedItem().toString());
            nd.setUserName(txtuser.getText());
            nd.setPass(txtpass.getText());
            nd.setHinh(personalImage);
            NhanVienDao dao = new NhanVienDao();
            if(dao.update(nd))
            {
                MessageDialogHelper.showMessageDialog(menuView, "Nhân viên đã đươc cập nhật!", "Thông báo !");
                LoadDataTable();
            }
            else
            {
                MessageDialogHelper.showConfirmDialog(menuView, "Nhân viên không được cập nhật do lỗi !","Cảnh báo!");
            }

        }
        catch( Exception e)
        {
            e.printStackTrace();
            MessageDialogHelper.showErrorDialog(menuView,e.getMessage(),"Lỗi!");
        }
    }//GEN-LAST:event_btnSuaNCCActionPerformed

    private void btnThemNCCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemNCCActionPerformed
        StringBuilder sb = new StringBuilder();
//        DataValdator.CheckDL(txtma, sb, "Mã nhân viên không được để trống !");
        DataValdator.CheckDL(txtten, sb, "Tên nhân viên không được để trống !");
        if( sb.length()>0)
        {
            MessageDialogHelper.showErrorDialog(this,sb.toString(), "Lỗi");
            return;
        }
        try
        {
            NguoiDung nd = new NguoiDung();
//            nd.setMaND(Integer.parseInt(txtma.getText()));
            nd.setTenND(txtten.getText());
            nd.setNgaySinh(txttuoi.getText());
            nd.setSoDT(txtsodt.getText());
            nd.setGioiTinh(rdonam.isSelected()?1:0);
            nd.setDiaChi(txtdiachi.getText());
            nd.setChucVu(txtchucvu.getSelectedItem().toString());
            nd.setUserName(txtuser.getText());
            nd.setPass(txtpass.getText());
            nd.setHinh(personalImage);
            NhanVienDao dao = new NhanVienDao();
            if(dao.insert(nd))
            {
                MessageDialogHelper.showMessageDialog(menuView, "Nhân viên đã đươc lưu", "Thông báo !");
                LoadDataTable();
            }
            else
            {
                MessageDialogHelper.showConfirmDialog(menuView, "Nhân viên không được lưu do lỗi !","Cảnh báo!");
            }

        }
        catch( Exception e)
        {
            e.printStackTrace();
            MessageDialogHelper.showErrorDialog(menuView,e.getMessage(),"Lỗi!");
        }
    }//GEN-LAST:event_btnThemNCCActionPerformed

    private void btntimkiem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btntimkiem1ActionPerformed
        try
        {
            NhanVienDao dao = new NhanVienDao();
            NguoiDung nd = dao.findTen(txtma1.getText());
            if(nd !=null)
            {
                txtma.setText(" " +nd.getMaND());
                txtten.setText(nd.getTenND());
                txttuoi.setText(nd.getNgaySinh());
                txtsodt.setText(nd.getSoDT());
                txtdiachi.setText(nd.getDiaChi());
                txtpass.setText(nd.getPass());
                txtuser.setText(nd.getUserName());
                txtchucvu.setSelectedItem(nd.getChucVu());
                rdonam.setSelected(nd.getGioiTinh()==1 ? true:false);
                if(nd.getHinh() !=null)
                {
                    Image img = ImageHelper.createiImage(nd.getHinh(),"jpg");
                    lblImage.setIcon(new ImageIcon(img));
                    personalImage =nd.getHinh();
                }
                else
                {
                    personalImage = nd.getHinh();
                    ImageIcon icon = new ImageIcon(
                        getClass().getResource(""));
                    lblImage.setIcon(icon);
                }

            }
            else
            {
                MessageDialogHelper.showMessageDialog(menuView,  "Không tim thấy sinh vien can tim -_- ", "Thông báo !");
            }
        }
        catch (Exception e) {
            e.printStackTrace();
            MessageDialogHelper.showErrorDialog(menuView,e.getMessage(),"Lỗi!");
        }

    }//GEN-LAST:event_btntimkiem1ActionPerformed

    private void txtma1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtma1KeyReleased

    }//GEN-LAST:event_txtma1KeyReleased

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        JFileChooser chooser = new JFileChooser();
        chooser.setFileFilter(new FileFilter()
            {
                public  boolean  accept( File f)
                {
                    if(f.isDirectory())
                    {
                        return  true;
                    }
                    else
                    {
                        return  f.getName().toLowerCase().endsWith(".jpg");
                    }
                }

                @Override
                public String getDescription() {
                    return " Image File (*.jpg)";
                }
            });
            // hop thoai
            if(chooser.showOpenDialog(menuView)== JFileChooser.CANCEL_OPTION)   {
                return;
            }
            File file =chooser.getSelectedFile();
            try
            {
                ImageIcon icon = new ImageIcon(file.getPath());
                Image img = ImageHelper.resize(icon.getImage(), 140, 150);
                ImageIcon resiIcon = new ImageIcon(img);
                lblImage.setIcon(resiIcon);
                //luu vao CSDL
                personalImage = ImageHelper.toByteArray(img,"jpg");
            }
            catch (IOException e) {
                e.printStackTrace();
                MessageDialogHelper.showErrorDialog(menuView,e.getMessage(),"Lỗi!");
            }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txtchucvuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtchucvuActionPerformed

    }//GEN-LAST:event_txtchucvuActionPerformed

    private void txtpassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtpassActionPerformed

    }//GEN-LAST:event_txtpassActionPerformed

    private void txtuserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtuserActionPerformed

    }//GEN-LAST:event_txtuserActionPerformed

    private void txttenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txttenActionPerformed

    }//GEN-LAST:event_txttenActionPerformed

    private void txtmaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtmaActionPerformed

    }//GEN-LAST:event_txtmaActionPerformed

    private void txtmaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtmaFocusLost

    }//GEN-LAST:event_txtmaFocusLost

    private void txtmaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtmaFocusGained

    }//GEN-LAST:event_txtmaFocusGained
       

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnReset;
    private javax.swing.JButton btnSuaNCC;
    private javax.swing.JButton btnThemNCC;
    private javax.swing.JButton btnXoaNCC;
    private javax.swing.JButton btntimkiem1;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel18;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblImage;
    private javax.swing.JRadioButton rbnu;
    private javax.swing.JRadioButton rdonam;
    private javax.swing.JTable tbbang;
    private javax.swing.JComboBox<String> txtchucvu;
    private javax.swing.JTextArea txtdiachi;
    private javax.swing.JTextField txtma;
    private javax.swing.JTextField txtma1;
    private javax.swing.JTextField txtpass;
    private javax.swing.JTextField txtsodt;
    private javax.swing.JTextField txtten;
    private javax.swing.JFormattedTextField txttuoi;
    private javax.swing.JTextField txtuser;
    // End of variables declaration//GEN-END:variables
}
