/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Dao.GiaoDichDatDao;
import Dao.GiaoDichNhaDao;
import Data.MessageDialogHelper;
import Model.GiaoDichDat;
import Model.GiaoDichNha;
import java.text.DecimalFormat;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author This PC
 */
public class ThongKeView extends javax.swing.JPanel {

    private List<GiaoDichDat> giaodich;
    private List<GiaoDichNha> nha;
    private DefaultTableModel tblModel = new DefaultTableModel();
    private DefaultTableModel tblModelnha = new DefaultTableModel();
    private MenuView menuView;
    String string;

    /**
     * Creates new form TK
     */
    public ThongKeView() {
        initComponents();

        Tong();
        tongso();
        initTable();
        LoadDataTable();

        Tong1();
        tongso1();
        initTable1();
        LoadDataTable1();
    }

    private void LoadDataTable() {
        try {
            GiaoDichDatDao dao = new GiaoDichDatDao();
            List<GiaoDichDat> list = dao.findAll();
            tblModel.setRowCount(0);
            int i = 1;
            for (GiaoDichDat it : list) {
                tblModel.addRow(new Object[]{
                    i++, it.getMaGDD(), it.getNgayGD(), it.getMaDat(),
                    it.getThanhToan()
                });
            }
            tblModel.fireTableDataChanged();
        } catch (Exception e) {
            e.printStackTrace();
            MessageDialogHelper.showErrorDialog(menuView, e.getMessage(), "Lỗi!");
        }
    }

    private void initTable() {
        tblModel = new DefaultTableModel();
        String[] columns = new String[]{"SoTT", "Mã GD", "Ngày GD", "Mã Đất", "Thành Tiền "};
        tblModel.setColumnIdentifiers(columns);
        tblbang1.setModel(tblModel);

    }

    private void LoadDataTable1() {
        try {
            GiaoDichNhaDao dao = new GiaoDichNhaDao();
            List<GiaoDichNha> list = dao.findAll();
            tblModelnha.setRowCount(0);
            int i = 1;
            for (GiaoDichNha it : list) {
                tblModelnha.addRow(new Object[]{
                    i++, it.getMaGDN(), it.getNgayGD(), it.getMaNha(),
                    it.getThanhToan()
                });
            }
            tblModelnha.fireTableDataChanged();
        } catch (Exception e) {
            e.printStackTrace();
            MessageDialogHelper.showErrorDialog(menuView, e.getMessage(), "Lỗi!");
        }
    }

    private void initTable1() {
        tblModelnha = new DefaultTableModel();
        String[] columns = new String[]{"SoTT", "Mã GD", "Ngày GD", "Mã Nhà", "Thành Tiền "};
        tblModelnha.setColumnIdentifiers(columns);
        tblbang2.setModel(tblModelnha);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        lblTong = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblbang1 = new javax.swing.JTable();
        lblTong1 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txttim = new javax.swing.JTextField();
        btntim = new javax.swing.JButton();
        btnReset = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel4 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        lblTong2 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblbang2 = new javax.swing.JTable();
        lblTong3 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        txttimnha = new javax.swing.JTextField();
        btntimnha = new javax.swing.JButton();
        btnReset1 = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();

        jPanel2.setBorder(new javax.swing.border.MatteBorder(null));
        jPanel2.setLayout(null);

        lblTong.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblTong.setText("Tổng Thu:  ");

        tblbang1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tblbang1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblbang1MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblbang1);

        lblTong1.setBackground(new java.awt.Color(255, 102, 51));
        lblTong1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblTong1.setText("Tổng số hóa đơn:  ");

        jLabel2.setText("Tìm kiếm theo ngày/tháng/năm");

        btntim.setText("Tìm Kiếm");
        btntim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btntimActionPerformed(evt);
            }
        });

        btnReset.setText("Reset");
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txttim, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(58, 58, 58)
                .addComponent(btntim)
                .addGap(36, 36, 36)
                .addComponent(btnReset)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txttim, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btntim)
                    .addComponent(btnReset))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel4.setText("Giao dịch đất");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jSeparator2)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 853, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(413, 413, 413)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblTong, javax.swing.GroupLayout.PREFERRED_SIZE, 379, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblTong1, javax.swing.GroupLayout.PREFERRED_SIZE, 379, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(229, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblTong1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblTong, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(153, 153, 153))
        );

        jPanel2.add(jPanel3);
        jPanel3.setBounds(20, 10, 1110, 620);

        jTabbedPane1.addTab("Giao dịch đất", jPanel2);

        jPanel1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jPanel1.setLayout(null);

        lblTong2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblTong2.setText("Tổng Thu:  ");

        tblbang2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tblbang2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblbang2MouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tblbang2);

        lblTong3.setBackground(new java.awt.Color(255, 102, 51));
        lblTong3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblTong3.setText("Tổng số hóa đơn:  ");

        jLabel3.setText("Tìm kiếm theo ngày/tháng/năm");

        btntimnha.setText("Tìm Kiếm");
        btntimnha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btntimnhaActionPerformed(evt);
            }
        });

        btnReset1.setText("Reset");
        btnReset1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReset1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txttimnha, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(58, 58, 58)
                .addComponent(btntimnha)
                .addGap(36, 36, 36)
                .addComponent(btnReset1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txttimnha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btntimnha)
                    .addComponent(btnReset1))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel1.setText("Giao dịch nhà");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jSeparator1)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 764, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(308, 308, 308)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblTong2, javax.swing.GroupLayout.PREFERRED_SIZE, 379, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblTong3, javax.swing.GroupLayout.PREFERRED_SIZE, 379, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(348, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23)
                .addComponent(lblTong3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblTong2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(156, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel5);
        jPanel5.setBounds(0, -8, 1140, 640);

        jTabbedPane1.addTab("Giao dịch nhà", jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1262, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 665, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void tblbang1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblbang1MouseClicked

    }//GEN-LAST:event_tblbang1MouseClicked

    private void btntimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btntimActionPerformed
        String Date = txttim.getText();
        if (Date.length() > 0) {
            try {
                giaodich = new GiaoDichDatDao().findbyDate(Date);
            } catch (Exception ex) {
                Logger.getLogger(ThongKeView.class.getName()).log(Level.SEVERE, null, ex);
            }
            tblModel.setRowCount(0);
            for (GiaoDichDat gd : giaodich) {
                tblModel.addRow(new Object[]{
                    tblbang1.getRowCount() + 1, gd.getMaGDD(), gd.getNgayGD(), gd.getMaDat(), gd.getThanhToan()
                });
            }
            Tong();
            tongso();
        }
    }//GEN-LAST:event_btntimActionPerformed

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
        txttim.setText("");
        LoadDataTable();
    }//GEN-LAST:event_btnResetActionPerformed

    private void tblbang2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblbang2MouseClicked

    }//GEN-LAST:event_tblbang2MouseClicked

    private void btntimnhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btntimnhaActionPerformed
        String Date = txttimnha.getText();
        if (Date.length() > 0) {
            try {
                nha = new GiaoDichNhaDao().findbyDate(Date);
            } catch (Exception ex) {
                Logger.getLogger(ThongKeView.class.getName()).log(Level.SEVERE, null, ex);
            }
            tblModelnha.setRowCount(0);
            for (GiaoDichNha gd : nha) {
                tblModelnha.addRow(new Object[]{
                    tblbang2.getRowCount() + 1, gd.getMaGDN(), gd.getNgayGD(), gd.getMaNha(), gd.getThanhToan()
                });
            }
            Tong1();
            tongso1();
        }
    }//GEN-LAST:event_btntimnhaActionPerformed

    private void btnReset1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReset1ActionPerformed
        txttimnha.setText("");
        LoadDataTable1();
    }//GEN-LAST:event_btnReset1ActionPerformed
    private void Tong() {
        DecimalFormat x = new DecimalFormat("###,###,###");
        int Tong = 0;

        for (int i = 0; i < tblbang1.getRowCount(); i++) {
            Tong += Float.parseFloat(tblbang1.getValueAt(i, 4).toString());

        }
        lblTong.setText("Tổng doanh thu: " + " " + x.format(Tong) + " " + "VND");
    }

    private void tongso() {
        DecimalFormat x = new DecimalFormat("###,###,###");
        int sohd = 0;
        int sc = tblbang1.getRowCount();
        for (int i = 0; i < sc; i++) {
            sohd += 1;
        }
        lblTong1.setText("Tổng số hóa đơn: " + " " + x.format(sohd) + " " + "HĐ");

    }

    private void Tong1() {
        DecimalFormat x = new DecimalFormat("###,###,###");
        int Tong = 0;

        for (int i = 0; i < tblbang2.getRowCount(); i++) {
            Tong += Float.parseFloat(tblbang2.getValueAt(i, 4).toString());

        }
        lblTong2.setText("Tổng doanh thu: " + " " + x.format(Tong) + " " + "VND");
    }

    private void tongso1() {
        DecimalFormat x = new DecimalFormat("###,###,###");
        int sohd = 0;
        int sc = tblbang2.getRowCount();
        for (int i = 0; i < sc; i++) {
            sohd += 1;
        }
        lblTong3.setText("Tổng số hóa đơn: " + " " + x.format(sohd) + " " + "HĐ");

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnReset;
    private javax.swing.JButton btnReset1;
    private javax.swing.JButton btntim;
    private javax.swing.JButton btntimnha;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel lblTong;
    private javax.swing.JLabel lblTong1;
    private javax.swing.JLabel lblTong2;
    private javax.swing.JLabel lblTong3;
    private javax.swing.JTable tblbang1;
    private javax.swing.JTable tblbang2;
    private javax.swing.JTextField txttim;
    private javax.swing.JTextField txttimnha;
    // End of variables declaration//GEN-END:variables
}
